[technote]
id = "DMTN-302"
series_id = "DMTN"
canonical_url = "https://dmtn-302.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-302"
github_default_branch = "main"
date_created = 2024-11-22T17:37:38Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Tim"
name.family = "Jenness"
internal_id = "jennesst"
orcid = "https://orcid.org/0000-0001-5982-167X"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
